### ISSUE TITLE
plipcmd segfaults with PDBID 1u6b

### ISSUE THREAD

**Issue by flobosg** [ssalentin/plip#2]
`plipcmd` throws a segmentation fault when PDB entry [1u6b](http://www.rcsb.org/pdb/explore.do?structureId=1u6b) is used as an input. I haven't tried to debug the problem yet, but may look into it later.

    $ plipcmd -v -i 1u6b

    **********************************************
    * Protein-Ligand Interaction Profiler v1.3.0 *
    **********************************************

    Checking status of PDB ID 1u6b ... entry is up to date.
    Downloading file from PDB ... file downloaded as /tmp/1u6b.pdb

    Starting analysis of 1u6b.pdb
    ===============================
    PDB structure successfully read.
    Excluded molecules as ligands: 5MU,A23,GTP
    Analyzing 4 ligands...

    K-MG-K-G-C-C-G-U-G-U... [RNA+ION] -- K:B:2 + MG:B:3 + K:B...
    -------------------------------------------------------------
      [Warning] Could not write SMILES for this ligand.
    Segmentation fault (core dumped)

- PLIP version 1.3.0
- Python 2.7.6
- Ubuntu 14.04

**Comment by ssalentin** [comment]
Thank you for your feedback. Apparently, the OBRing.GetType() function is causing the segfault in this case. So it is an problem with OpenBabel. I will probably deactivate the deduction of ring types with OpenBabel until this issue is fixed and name the type of the ring as '5-member', '6-member', etc. I will try to release a fix today.

**Comment by ssalentin** [comment]
Issue has been fixed in Bugfix Release v1.3.0a ( 8929c9d ).

**Comment by flobosg** [comment]
Thank you! I'm using Open Babel 2.3.2+dfsg-1.1 by the way.
